language: c
compiler:
    - gcc
    - clang

os:
    - linux
    - osx

before_script:
    - ./bootstrap

script:
    - ./configure
    - make
    - make check
    - ./test2_libxls test/files/test2.xls
    - ./configure --without-iconv
    - make
    - make check
